### Preprocess Phase Test
POST http://localhost:3000/api/batchWeight/preprocess/
Content-Type: application/json

{
    "weightBeforeCooking": 200,
    "prodId":5409
}

### Cooking Phase Test
POST http://localhost:3000/api/batchWeight/cooking/1234|2024-11-09
Content-Type: application/json

{
    "weightAfterCooking": 188,
    "storageStart": "2024-11-09T10:00:00Z"
}

### Storage Phase Test
POST http://localhost:3000/api/batchWeight/storage/1234|2024-11-09
Content-Type: application/json

{
    "weightAfterStorage": 100,
    "storageEnd": "2024-11-10T10:00:00Z"
}

### Fetch Batch Details Test
GET http://localhost:3000/api/batchWeight/
###
DELETE http://localhost:3000/api/batchWeight/

